#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##          (Windows/Cygwin/GNU gfortran Version)         ##
#  ##                                                        ##
#  ############################################################
#
#
gfortran -c -g  -O active.f
gfortran -c -g  -O alchemy.f
gfortran -c -g  -O analysis.f
gfortran -c -g  -O analyze.f
gfortran -c -g  -O angles.f
gfortran -c -g  -O anneal.f
gfortran -c -g  -O archive.f
gfortran -c -g  -O attach.f
gfortran -c -g  -O bar.f
gfortran -c -g  -O basefile.f
gfortran -c -g  -O beeman.f
gfortran -c -g  -O bicubic.f
gfortran -c -g  -O bitors.f
gfortran -c -g  -O bonds.f
gfortran -c -g  -O born.f
gfortran -c -g  -O bounds.f
gfortran -c -g  -O bussi.f
gfortran -c -g  -O calendar.f
gfortran -c -g  -O center.f
gfortran -c -g  -O chkpole.f
gfortran -c -g  -O chkring.f
gfortran -c -g  -O chkxyz.f
gfortran -c -g  -O cholesky.f
gfortran -c -g  -O clock.f
gfortran -c -g  -O cluster.f
gfortran -c -g  -O column.f
gfortran -c -g  -O command.f
gfortran -c -g  -O connect.f
gfortran -c -g  -O connolly.f
gfortran -c -g  -O control.f
gfortran -c -g  -O correlate.f
gfortran -c -g  -O crystal.f
gfortran -c -g  -O cspline.f
gfortran -c -g  -O cutoffs.f
gfortran -c -g  -O deflate.f
gfortran -c -g  -O delete.f
gfortran -c -g  -O diagq.f
gfortran -c -g  -O diffeq.f
gfortran -c -g  -O diffuse.f
gfortran -c -g  -O distgeom.f
gfortran -c -g  -O document.f
gfortran -c -g  -O dynamic.f
gfortran -c -g  -O eangang.f
gfortran -c -g  -O eangang1.f
gfortran -c -g  -O eangang2.f
gfortran -c -g  -O eangang3.f
gfortran -c -g  -O eangle.f
gfortran -c -g  -O eangle1.f
gfortran -c -g  -O eangle2.f
gfortran -c -g  -O eangle3.f
gfortran -c -g  -O ebond.f
gfortran -c -g  -O ebond1.f
gfortran -c -g  -O ebond2.f
gfortran -c -g  -O ebond3.f
gfortran -c -g  -O ebuck.f
gfortran -c -g  -O ebuck1.f
gfortran -c -g  -O ebuck2.f
gfortran -c -g  -O ebuck3.f
gfortran -c -g  -O echarge.f
gfortran -c -g  -O echarge1.f
gfortran -c -g  -O echarge2.f
gfortran -c -g  -O echarge3.f
gfortran -c -g  -O echgdpl.f
gfortran -c -g  -O echgdpl1.f
gfortran -c -g  -O echgdpl2.f
gfortran -c -g  -O echgdpl3.f
gfortran -c -g  -O edipole.f
gfortran -c -g  -O edipole1.f
gfortran -c -g  -O edipole2.f
gfortran -c -g  -O edipole3.f
gfortran -c -g  -O egauss.f
gfortran -c -g  -O egauss1.f
gfortran -c -g  -O egauss2.f
gfortran -c -g  -O egauss3.f
gfortran -c -g  -O egeom.f
gfortran -c -g  -O egeom1.f
gfortran -c -g  -O egeom2.f
gfortran -c -g  -O egeom3.f
gfortran -c -g  -O ehal.f
gfortran -c -g  -O ehal1.f
gfortran -c -g  -O ehal2.f
gfortran -c -g  -O ehal3.f
gfortran -c -g  -O eimprop.f
gfortran -c -g  -O eimprop1.f
gfortran -c -g  -O eimprop2.f
gfortran -c -g  -O eimprop3.f
gfortran -c -g  -O eimptor.f
gfortran -c -g  -O eimptor1.f
gfortran -c -g  -O eimptor2.f
gfortran -c -g  -O eimptor3.f
gfortran -c -g  -O elj.f
gfortran -c -g  -O elj1.f
gfortran -c -g  -O elj2.f
gfortran -c -g  -O elj3.f
gfortran -c -g  -O embed.f
gfortran -c -g  -O emetal.f
gfortran -c -g  -O emetal1.f
gfortran -c -g  -O emetal2.f
gfortran -c -g  -O emetal3.f
gfortran -c -g  -O emm3hb.f
gfortran -c -g  -O emm3hb1.f
gfortran -c -g  -O emm3hb2.f
gfortran -c -g  -O emm3hb3.f
gfortran -c -g  -O empole.f
gfortran -c -g  -O empole1.f
gfortran -c -g  -O empole2.f
gfortran -c -g  -O empole3.f
gfortran -c -g  -O energy.f
gfortran -c -g  -O eopbend.f
gfortran -c -g  -O eopbend1.f
gfortran -c -g  -O eopbend2.f
gfortran -c -g  -O eopbend3.f
gfortran -c -g  -O eopdist.f
gfortran -c -g  -O eopdist1.f
gfortran -c -g  -O eopdist2.f
gfortran -c -g  -O eopdist3.f
gfortran -c -g  -O epitors.f
gfortran -c -g  -O epitors1.f
gfortran -c -g  -O epitors2.f
gfortran -c -g  -O epitors3.f
gfortran -c -g  -O erf.f
gfortran -c -g  -O erxnfld.f
gfortran -c -g  -O erxnfld1.f
gfortran -c -g  -O erxnfld2.f
gfortran -c -g  -O erxnfld3.f
gfortran -c -g  -O esolv.f
gfortran -c -g  -O esolv1.f
gfortran -c -g  -O esolv2.f
gfortran -c -g  -O esolv3.f
gfortran -c -g  -O estrbnd.f
gfortran -c -g  -O estrbnd1.f
gfortran -c -g  -O estrbnd2.f
gfortran -c -g  -O estrbnd3.f
gfortran -c -g  -O estrtor.f
gfortran -c -g  -O estrtor1.f
gfortran -c -g  -O estrtor2.f
gfortran -c -g  -O estrtor3.f
gfortran -c -g  -O etors.f
gfortran -c -g  -O etors1.f
gfortran -c -g  -O etors2.f
gfortran -c -g  -O etors3.f
gfortran -c -g  -O etortor.f
gfortran -c -g  -O etortor1.f
gfortran -c -g  -O etortor2.f
gfortran -c -g  -O etortor3.f
gfortran -c -g  -O eurey.f
gfortran -c -g  -O eurey1.f
gfortran -c -g  -O eurey2.f
gfortran -c -g  -O eurey3.f
gfortran -c -g  -O evcorr.f
gfortran -c -g  -O extra.f
gfortran -c -g  -O extra1.f
gfortran -c -g  -O extra2.f
gfortran -c -g  -O extra3.f
gfortran -c -g  -O fatal.f
gfortran -c -g  -O fft3d.f
gfortran -c -g  -O fftpack.f
gfortran -c -g  -O field.f
gfortran -c -g  -O final.f
gfortran -c -g  -O flatten.f
gfortran -c -g  -O freeunit.f
gfortran -c -g  -O gda.f
gfortran -c -g  -O geometry.f
gfortran -c -g  -O getint.f
gfortran -c -g  -O getkey.f
gfortran -c -g  -O getmol.f
gfortran -c -g  -O getmol2.f
gfortran -c -g  -O getnumb.f
gfortran -c -g  -O getpdb.f
gfortran -c -g  -O getprm.f
gfortran -c -g  -O getref.f
gfortran -c -g  -O getstring.f
gfortran -c -g  -O gettext.f
gfortran -c -g  -O getword.f
gfortran -c -g  -O getxyz.f
gfortran -c -g  -O ghmcstep.f
gfortran -c -g  -O gradient.f
gfortran -c -g  -O gradrgd.f
gfortran -c -g  -O gradrot.f
gfortran -c -g  -O groups.f
gfortran -c -g  -O grpline.f
gfortran -c -g  -O gyrate.f
gfortran -c -g  -O hessian.f
gfortran -c -g  -O hessrgd.f
gfortran -c -g  -O hessrot.f
gfortran -c -g  -O hybrid.f
gfortran -c -g  -O image.f
gfortran -c -g  -O impose.f
gfortran -c -g  -O induce.f
gfortran -c -g  -O inertia.f
gfortran -c -g  -O initatom.f
gfortran -c -g  -O initial.f
gfortran -c -g  -O initprm.f
gfortran -c -g  -O initres.f
gfortran -c -g  -O initrot.f
gfortran -c -g  -O insert.f
gfortran -c -g  -O intedit.f
gfortran -c -g  -O intxyz.f
gfortran -c -g  -O invbeta.f
gfortran -c -g  -O invert.f
gfortran -c -g  -O jacobi.f
gfortran -c -g  -O kangang.f
gfortran -c -g  -O kangle.f
gfortran -c -g  -O katom.f
gfortran -c -g  -O kbond.f
gfortran -c -g  -O kcharge.f
gfortran -c -g  -O kdipole.f
gfortran -c -g  -O kewald.f
gfortran -c -g  -O kextra.f
gfortran -c -g  -O kgeom.f
gfortran -c -g  -O kimprop.f
gfortran -c -g  -O kimptor.f
gfortran -c -g  -O kinetic.f
gfortran -c -g  -O kmetal.f
gfortran -c -g  -O kmpole.f
gfortran -c -g  -O kopbend.f
gfortran -c -g  -O kopdist.f
gfortran -c -g  -O korbit.f
gfortran -c -g  -O kpitors.f
gfortran -c -g  -O kpolar.f
gfortran -c -g  -O ksolv.f
gfortran -c -g  -O kstrbnd.f
gfortran -c -g  -O kstrtor.f
gfortran -c -g  -O ktors.f
gfortran -c -g  -O ktortor.f
gfortran -c -g  -O kurey.f
gfortran -c -g  -O kvdw.f
gfortran -c -g  -O lattice.f
gfortran -c -g  -O lbfgs.f
gfortran -c -g  -O lights.f
gfortran -c -g  -O makeint.f
gfortran -c -g  -O makeref.f
gfortran -c -g  -O makexyz.f
gfortran -c -g  -O maxwell.f
gfortran -c -g  -O mdinit.f
gfortran -c -g  -O mdrest.f
gfortran -c -g  -O mdsave.f
gfortran -c -g  -O mdstat.f
gfortran -c -g  -O mechanic.f
gfortran -c -g  -O merge.f
gfortran -c -g  -O minimize.f
gfortran -c -g  -O minirot.f
gfortran -c -g  -O minrigid.f
gfortran -c -g  -O molecule.f
gfortran -c -g  -O molxyz.f
gfortran -c -g  -O moments.f
gfortran -c -g  -O monte.f
gfortran -c -g  -O mutate.f
gfortran -c -g  -O nblist.f
gfortran -c -g  -O newton.f
gfortran -c -g  -O newtrot.f
gfortran -c -g  -O nextarg.f
gfortran -c -g  -O nexttext.f
gfortran -c -g  -O nose.f
gfortran -c -g  -O nspline.f
gfortran -c -g  -O nucleic.f
gfortran -c -g  -O number.f
gfortran -c -g  -O numeral.f
gfortran -c -g  -O numgrad.f
gfortran -c -g  -O ocvm.f
gfortran -c -g  -O openend.f
gfortran -c -g  -O optimize.f
gfortran -c -g  -O optirot.f
gfortran -c -g  -O optrigid.f
gfortran -c -g  -O optsave.f
gfortran -c -g  -O orbital.f
gfortran -c -g  -O orient.f
gfortran -c -g  -O orthog.f
gfortran -c -g  -O overlap.f
gfortran -c -g  -O path.f
gfortran -c -g  -O pdbxyz.f
gfortran -c -g  -O picalc.f
gfortran -c -g  -O pmestuff.f
gfortran -c -g  -O pmpb.f
gfortran -c -g  -O polarize.f
gfortran -c -g  -O poledit.f
gfortran -c -g  -O polymer.f
gfortran -c -g  -O potential.f
gfortran -c -g  -O precise.f
gfortran -c -g  -O pressure.f
gfortran -c -g  -O prmedit.f
gfortran -c -g  -O prmkey.f
gfortran -c -g  -O promo.f
gfortran -c -g  -O protein.f
gfortran -c -g  -O prtdyn.f
gfortran -c -g  -O prterr.f
gfortran -c -g  -O prtint.f
gfortran -c -g  -O prtmol2.f
gfortran -c -g  -O prtpdb.f
gfortran -c -g  -O prtprm.f
gfortran -c -g  -O prtseq.f
gfortran -c -g  -O prtxyz.f
gfortran -c -g  -O pss.f
gfortran -c -g  -O pssrigid.f
gfortran -c -g  -O pssrot.f
gfortran -c -g  -O quatfit.f
gfortran -c -g  -O radial.f
gfortran -c -g  -O random.f
gfortran -c -g  -O rattle.f
gfortran -c -g  -O readdyn.f
gfortran -c -g  -O readgau.f
gfortran -c -g  -O readint.f
gfortran -c -g  -O readmol.f
gfortran -c -g  -O readmol2.f
gfortran -c -g  -O readpdb.f
gfortran -c -g  -O readprm.f
gfortran -c -g  -O readseq.f
gfortran -c -g  -O readxyz.f
gfortran -c -g  -O iqbal.f
gfortran -c -g  -O replica.f
gfortran -c -g  -O respa.f
gfortran -c -g  -O rgdstep.f
gfortran -c -g  -O rings.f
gfortran -c -g  -O rmsfit.f
gfortran -c -g  -O rotlist.f
gfortran -c -g  -O rotpole.f
gfortran -c -g  -O saddle.f
gfortran -c -g  -O scan.f
gfortran -c -g  -O sdstep.f
gfortran -c -g  -O search.f
gfortran -c -g  -O server.f
gfortran -c -g  -O shakeup.f
gfortran -c -g  -O sigmoid.f
gfortran -c -g  -O sktstuff.f
gfortran -c -g  -O sniffer.f
gfortran -c -g  -O sort.f
gfortran -c -g  -O spacefill.f
gfortran -c -g  -O spectrum.f
gfortran -c -g  -O square.f
gfortran -c -g  -O suffix.f
gfortran -c -g  -O superpose.f
gfortran -c -g  -O surface.f
gfortran -c -g  -O surfatom.f
gfortran -c -g  -O switch.f
gfortran -c -g  -O sybylxyz.f
gfortran -c -g  -O temper.f
gfortran -c -g  -O testgrad.f
gfortran -c -g  -O testhess.f
gfortran -c -g  -O testpair.f
gfortran -c -g  -O testpol.f
gfortran -c -g  -O testrot.f
gfortran -c -g  -O timer.f
gfortran -c -g  -O timerot.f
gfortran -c -g  -O tncg.f
gfortran -c -g  -O torphase.f
gfortran -c -g  -O torque.f
gfortran -c -g  -O torsfit.f
gfortran -c -g  -O torsions.f
gfortran -c -g  -O trimtext.f
gfortran -c -g  -O unitcell.f
gfortran -c -g  -O valence.f
gfortran -c -g  -O verlet.f
gfortran -c -g  -O version.f
gfortran -c -g  -O vibbig.f
gfortran -c -g  -O vibrate.f
gfortran -c -g  -O vibrot.f
gfortran -c -g  -O volume.f
gfortran -c -g  -O xtalfit.f
gfortran -c -g  -O xtalmin.f
gfortran -c -g  -O xyzatm.f
gfortran -c -g  -O xyzedit.f
gfortran -c -g  -O xyzint.f
gfortran -c -g  -O xyzpdb.f
gfortran -c -g  -O xyzsybyl.f
gfortran -c -g  -O zatom.f
